#cloud-config
package_upgrade: true
packages:
  - docker.io
  - docker-compose
  - jq
  - python3-pip
  - python3.10-venv
groups:
  - docker
users:
  - default
  - name: ${UserName}
    groups: docker
runcmd:
  - sudo -H -u ${UserName} bash -c 'git clone ${GitRepoUrl} $HOME/${GitRepoName}'
  - echo ${KengContainerRegistryToken} | docker login ${KengContainerRegistry} -u ${KengContainerRegistryUser} --password-stdin
  - docker pull ${KengControllerImage}
  - docker pull ${KengLicenseImage}
  - docker pull ${KengTrafficEngineImage}
  - docker images
  - sudo -H -u ${UserName} bash -c 'echo "alias python=python3" >> $HOME/.bashrc'
  - sudo -H -u ${UserName} bash -c 'echo "alias pip=pip3" >> $HOME/.bashrc'
  - python3 -m pip install --upgrade pip
  - python3 --version
  - pip3 --version
  - sudo -H -u ${UserName} bash -c 'python3 -m venv $HOME/venv'
  - sudo -H -u ${UserName} bash -c 'source $HOME/venv/bin/activate; pip install -r $HOME/${GitRepoName}/${GitRepoExecPath}/py/requirements.txt; deactivate'
  - chmod +x /home/${UserName}/${GitRepoName}/${GitRepoExecPath}/*.sh
  - chmod +x /home/${UserName}/${GitRepoName}/${GitRepoDeployPath}/setup.sh
merge_how:
 - name: list
   settings: [append]
 - name: dict
   settings: [no_replace, recurse_list]