version: '3'

services:

  KENG-License-Server:
    image: docker-local-athena.artifactory.it.keysight.com/keng-license-server:latest
    container_name: keng-license-server
    restart: always
    ports:
      - "7443:7443"
      - "9443:9443"
    command: --accept-eula

  controller:
    image: ghcr.io/open-traffic-generator/keng-controller:0.1.0-3
    command: --accept-eula --http-port 8443  --license-servers=localhost
    network_mode: "host"
    restart: always

  TE1-5551:
    image: docker-local-ixvm-lbj.artifactorylbj.it.keysight.com/athena-traffic-engine:1.6.0.101-msft-mana11
    command: sleep infinity
    network_mode: "host"
    privileged: true
    restart: "no"
    volumes:
      - /mnt/huge:/mnt/huge
      - /sys/kernel/mm/hugepages:/sys/kernel/mm/hugepages
      - /sys/bus/pci/drivers:/sys/bus/pci/drivers
      - /sys/devices/system/node:/sys/devices/system/node
      - /dev:/dev
    environment:
    - OPT_LISTEN_PORT=5551
    - ARG_IFACE_LIST=pci@2ea4:00:02.0 pci@5f07:00:02.0
    - BUS_INFO1=2ea4:00:02.0
    - BUS_INFO2=5f07:00:02.0
    - MANA_MAC1=00:15:5d:06:21:06
    - MANA_MAC2=00:15:5d:06:21:0d
    - ARG_CORE_LIST="0 1 2 3 4"
