#cloud-config
package_upgrade: true
packages:
  - docker.io
  - docker-compose
  - jq
  - python3-pip
  - python3.10-venv
  - linux-modules-extra-azure
groups:
  - docker
users:
  - default
  - name: ${UserName}
    groups: docker
runcmd:
  - sudo -H -u ${UserName} bash -c 'git clone ${GitRepoUrl} $HOME/${GitRepoName}'
  - echo ${KengContainerRegistryToken} | docker login ${KengContainerRegistry} -u ${KengContainerRegistryUser} --password-stdin
  - docker pull ${KengControllerImage}
  - docker pull ${KengLicenseImage}
  - docker pull ${KengTrafficEngineImage}
  - docker images
  - sudo -H -u ${UserName} bash -c 'echo "alias python=python3" >> $HOME/.bashrc'
  - sudo -H -u ${UserName} bash -c 'echo "alias pip=pip3" >> $HOME/.bashrc'
  - python3 -m pip install --upgrade pip
  - python3 --version
  - pip3 --version
  - sudo -H -u ${UserName} bash -c 'python3 -m venv $HOME/venv'
  - sudo -H -u ${UserName} bash -c 'source $HOME/venv/bin/activate; pip install -r $HOME/${GitRepoName}/${GitRepoExecPath}/py/requirements.txt; deactivate'
  - AgentBusInfoList=$(lshw -C network -json | jq '.[] | select( .businfo != null)' | jq -r .businfo)
  - AgentEth1BusInfo=$(echo $AgentBusInfoList | awk '{print $1}')
  - sed -i "s/pci@eth1/$AgentEth1BusInfo/g" /home/${UserName}/${GitRepoName}/${GitRepoDeployPath}/docker-compose.yaml
  - chmod +x /home/${UserName}/${GitRepoName}/${GitRepoExecPath}/*.sh
  - chmod +x /home/${UserName}/${GitRepoName}/${GitRepoDeployPath}/setup.sh
  - /home/${UserName}/${GitRepoName}/${GitRepoDeployPath}/setup.sh
  - modprobe mana_ib
  - sudo -H -u ${UserName} bash -c 'docker-compose -f $HOME/${GitRepoName}/${GitRepoDeployPath}/docker-compose.yaml up -d'
  - sudo -H -u ${UserName} bash -c 'docker-compose -f $HOME/${GitRepoName}/${GitRepoDeployPath}/docker-compose.yaml ps'
merge_how:
 - name: list
   settings: [append]
 - name: dict
   settings: [no_replace, recurse_list]