version: '3'

services:

  controller:
    image: ghcr.io/open-traffic-generator/keng-controller:0.1.0-3
    command: --accept-eula --http-port 8443
    network_mode: "host"
    restart: always

  TE1-5551:
    image: ghcr.io/open-traffic-generator/ixia-c-traffic-engine:1.6.0.85
    network_mode: "host"
    privileged: true
    restart: "no"
    environment:
    - OPT_LISTEN_PORT=5551
    - ARG_IFACE_LIST=virtual@af_packet,eth1
    - OPT_NO_HUGEPAGES=Yes